name: 'Hakai Dataset Repository Standard Tests'
description: 'Run a series of tests on a dataset repository to ensure it meets the Hakai Institute standards.'
inputs:
  dir:  # id of input
    description: 'base directory where to run the tests'
    required: true
    default: '.'
  config-file:
    description: 'Path to the repository configuration file'
    required: true
    default: 'config.yaml'
  token:
    description: 'GitHub token'
    required: true
outputs:
  tests-results:
    description: 'Tests results'
    value: ${{ steps.tests.outputs.results }}
runs:
  using: "composite"
  steps:
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Hakai Tests
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install git+https://HakaiInstitute:${{ inputs.token }}@github.com/HakaiInstitute/hakai-datasets-repo-standard-tests.git
    - name: Run tests
      shell: bash
      id: tests
      run: |
        python hakai_data_repo_tests --dir='${{ inputs.dir }}' --config-path='${{ inputs.config-file }}' --junit-xml='test-results.xml' > test_results.txt
        echo "results='$(cat test_results.txt)'" >> $GITHUB_ENV

    - name: Surface failing tests
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: test-results.xml