name: Test dataset

on:
  pull_request:
    branches: master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Hakai Tests
        run: |
          python -m pip install --upgrade pip
          pip install git+https://HakaiInstitute:${{secrets.CI_TOKEN}}@github.com/HakaiInstitute/hakai-datasets-repo-standard-tests.git
      - name: Test with pytest
        working-directory: ./test_repo
        run: |
          python hakai_data_repo_tests --dir=test_repo
