name: Test Composite Action
on:
  push:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: HakaiInstitute/hakai-pruth-mooring-data
          branch: production
          token: ${{ secrets.CI_TOKEN}}
    
      - name: Run hakai tests composite action development branch
        if: ${{ github.ref_name== 'development' }}
        uses: hakaiinstitute/hakai-datasets-repo-standard-tests@development
        with:
            token: ${{ secrets.CI_TOKEN}}
