name: Test dataset

on:
  pull_request:
    branches: master
  push:
    branches: 
        - master
        - development
        - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Hakai Tests
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Test with pytest
        working-directory: ./test_repo
        run: |
          pytest --pyargs hakai_data_repo_tests
